params:
  - group: Style
    items:
      - key: marginTop
        name: Margin Top
        type: integer
        defaultValue: 0
        ui: input
      - key: marginBottom
        name: Margin Bottom
        type: integer
        defaultValue: 0
        ui: input
      - key: marginLeft
        name: Margin Left
        type: integer
        defaultValue: 0
        ui: input
      - key: marginRight
        name: Margin Right
        type: integer
        defaultValue: 0
        ui: input
  - group: Parameters
    items:
      - key: defaultExpansion
        name: Default Expansion
        type: string
        ui: select
        options:
          - expanded
          - collapsed
        defaultValue: expanded
      - key: title
        name: Title
        type: string
        ui: input
        defaultValue: Panel Title