params:
  - group: Parameters
    items:
      - key: ratio
        name: Ratio
        type: string
        ui: select
        options:
          - "1:2"
          - "1:3"
          - "1:5"
          - "2:1"
          - "3:1"
          - "5:1"
        defaultValue: "3:1"