params:
  - group: Style
    items:
      - key: width
        name: Width
        type: integer
        ui: input
        defaultValue: 500
      - key: height
        name: Height
        type: integer
        ui: input
        defaultValue: 500
  - group: Parameters
    items:
      - key: rootName
        name: Root Node Name
        type: string
        ui: input
        defaultValue: "root"
      - key: nodes
        name: Tree Nodes
        type: tree
        ui: tree-editor
        defaultValue:
          - id: "1"
            name: node 1
            children:
              - id: "1-1"
                name: node 1-1
                children:
                  - id: "1-1-1"
                    name: node 1-1-1
                  - id: "1-1-2"
                    name: node 1-1-2
              - id: "1-2"
                name: node 1-2
          - id: "2"
            name: node 2
            children:
              - id: "2-1"
                name: node 2-1
              - id: "2-2"
                name: node 2-2
events:
  - key: onNodeClick
    name: onNodeClick
    args:
      - name: nodeName
        type: string
        required: true