params:
  - group: Style
    items:
      - key: marginTop
        name: Margin Top
        type: integer
        defaultValue: 5
        ui: input
      - key: marginBottom
        name: Margin Bottom
        type: integer
        defaultValue: 5
        ui: input
      - key: marginLeft
        name: Margin Left
        type: integer
        defaultValue: 5
        ui: input
      - key: marginRight
        name: Margin Right
        type: integer
        defaultValue: 5
        ui: input
  - group: Parameters
    items:
      - key: text
        name: Text
        type: string
        ui: input
        defaultValue: "Label Text"
      - key: fontSize
        name: Font Size
        type: integer
        defaultValue: 20
        ui: input
      - key: fontWeight
        name: Font Weight
        type: string
        ui: select
        options:
          - regular
          - bold
        defaultValue: regular
      - key: color
        name: Color
        type: string
        ui: color-picker
        defaultValue: "#000000"