params:
  - group: Parameters
    items:
      - key: columnCount
        name: Column Coumt
        type: integer
        ui: select
        options:
          - 1
          - 2
          - 3
          - 4
          - 6
        defaultValue: 2
